### ISSUE TITLE
Create Next.js App

### ISSUE THREAD

**Issue by qjimmy** [daniloorozco/boxdrop#1]
# Platform bootstrapping

As discussed, our main framework of choice is Next.js, an improved version of React without its flaws. 
Creating the app will generate boilerplate code for now, which is good to start with.

First, go into the root directory of this project and follow the steps here:

- `yarn create next-app client` This will create a folder named client which will hold our client side app
- Please convert all the js files under `/pages` to the `.ts` extension. We will be using Typescript to prevent bugs as early as possible. When you convert the files, you can change directory in the `client` folder and run `yarn start`. They will automatically generate a typescript config file for us :)

**Comment by daniloroz** [comment]
Task **completed**. Typescript config files generated. (See most recent commit).
