### ISSUE TITLE
Add Redux to our application

### ISSUE THREAD

**Issue by qjimmy** [daniloorozco/boxdrop#3]
# State Management

One of the main problems that single page applications tend to face is having some sort of globalized app state that is accessible to every part in the component tree. 

Redux is a solution that implements the singleton pattern in order to solve this problem. Concept is simple. Instead of components communicating with each other to know each other's states, components can send their states to something called a redux store. From that store, any component can easily access whatever available state there is.

---

For React apps, we'll need to install:

- redux
- react-redux
- redux-devtools-extension
- redux-observable

`yarn add redux react-redux redux-observable`

---

The redux package provides a basic API to set the store and reducers. The react-redux package provides use with a `<Provider store={/* store constant here */} />` component to wrap around our App's entry point. It also provides hooks such as `useSelector` to pick states from the store. The redux-observable package is for async side effects, since there is no async capacities in redux due to the requirement for reducers to be pure functions.

---

High level diagram of how redux works:

![how-redux-works](https://user-images.githubusercontent.com/30666844/112733119-6dd92f80-8f14-11eb-8b40-de13d1b5d514.png)

---

### Acceptance Criterias

For the scope of this ticket, here are the AC:

- Initialize an empty store
- import that store constant into the _app.tsx
- Wrap the `<Component />` with the `<Provider store={/* store you imported here */} >`
- Install the redux devtools browser add on. The one for Chrome can be found [here](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en).
- Look up how to set up our store to be listened by the redux add-on. [Section 1.3 from this](https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm) is relevant to us.

**Comment by daniloroz** [comment]
Added Redux Successfully.
