### ISSUE TITLE
Navbar + Sign up page and login page

### ISSUE THREAD

**Issue by qjimmy** [daniloorozco/boxdrop#5]
# Navbar + Sign up page and login page

**AC:**

- Sign up page and Login page should be on routes `/signup` and `/login` respectively.
- The pages shouldn't do anything for now when we press on buttons, this is purely UI/UX related.
- Implement the start of the navbar. Eventually, the Navbar will be augmented with more data such as user profile info.
- Using the components from @chakra-ui/react will speed up process or you can use css if you prefer

Somn like this shi but just similar to the skeleton/structure, don't worry about most details

<img width="1336" alt="Screen Shot 2021-04-04 at 12 35 26 AM" src="https://user-images.githubusercontent.com/30666844/113498731-b4fb8d80-94dd-11eb-98b2-f712bd440660.png">

**Comment by daniloroz** [comment]
Completed Sign Up, Login, and Navbar.
